# Generated by Django 2.1 on 2018-08-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tribe_name', models.CharField(max_length=50)),
                ('tribe_description', models.CharField(max_length=250)),
                ('tribe_location', models.CharField(max_length=250)),
                ('tribe_member_count', models.IntegerField()),
                ('tribe_tags', models.CharField(max_length=250)),
            ],
        ),
    ]
