# Generated by Django 2.1 on 2018-08-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribe', '0002_tribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
