# Generated by Django 2.1 on 2018-09-02 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribe', '0007_tribe_tribe_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribe',
            name='tribe_owner',
        ),
    ]
